#!/bin/bash

CWD=$(pwd)
DJANGODIR=$CWD
DJANGO_SETTINGS_MODULE=settings.prod_settings    # which settings file should Django use
VENV=~/virtualenvs/scamera-v2/bin/

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
source ${VENV}activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$CWD:$PYTHONPATH
