#!/bin/bash

CWD=$(pwd)
DJANGODIR=$CWD/app
DJANGO_SETTINGS_MODULE=settings.dev_settings    # which settings file should Django use
VENV=~/.virtualenvs/camera/bin/

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
source ${VENV}activate
cd $DJANGODIR
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$CWD:$PYTHONPATH

python manage.py migrate
python manage.py loaddata auth
python manage.py loaddata ftpd
python manage.py loaddata notifications