#!/bin/bash

CWD=$(pwd)
DJANGODIR=$CWD
DJANGO_SETTINGS_MODULE=settings.dev_settings    # which settings file should Django use
VENV=~/.virtualenvs/camera/bin/

BOTNAME=scamera_bot

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
source ${VENV}activate

# cd $DJANGODIR
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$CWD:$PYTHONPATH

exec python manage.py runtelegrambot -b $BOTNAME 