# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20160918_0231'),
        ('ftpd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTPDServerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_notification_handlers', models.ManyToManyField(to='notifications.TelegramNotificationHandler')),
            ],
        ),
    ]
