# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftpd', '0002_ftpdserverconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftpdserverconfig',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Start/Stop accepting new FTP connections'),
        ),
    ]
