# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleDetectorTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('initial', 'initial'), ('running', 'running'), ('finished', 'finished')], default='initial', max_length=10)),
            ],
        ),
    ]
