# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleDetectorTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Test', max_length=50)),
                ('state', models.CharField(choices=[('initial', 'initial'), ('running', 'running'), ('finished', 'finished'), ('failed', 'failed')], default='initial', max_length=10)),
                ('settings', models.TextField(default=images.models.settings_asstring)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('running_timestamp', models.DateTimeField(null=True, verbose_name='Executed')),
                ('time_took', models.FloatField(blank=True, default=0.0)),
                ('positive_samples_dir', models.CharField(max_length=150)),
                ('negative_samples_dir', models.CharField(max_length=150)),
                ('save_enhaced_images', models.BooleanField(default=False)),
                ('positive_samples_count', models.PositiveIntegerField(default=0, verbose_name='Positive Samples')),
                ('negative_samples_count', models.PositiveIntegerField(default=0, verbose_name='Negative Samples')),
                ('true_positives', models.PositiveIntegerField(default=0, verbose_name='TP')),
                ('true_negatives', models.PositiveIntegerField(default=0, verbose_name='TN')),
                ('false_positives', models.PositiveIntegerField(default=0, verbose_name='FP')),
                ('false_negatives', models.PositiveIntegerField(default=0, verbose_name='FN')),
                ('_accuracy', models.FloatField(default=0.0)),
                ('_total_samples_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
