# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopledetectortest',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peopledetectortest',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peopledetectortest',
            name='false_negatives',
            field=models.PositiveIntegerField(default=0, verbose_name='FN'),
        ),
        migrations.AddField(
            model_name='peopledetectortest',
            name='false_positives',
            field=models.PositiveIntegerField(default=0, verbose_name='FP'),
        ),
        migrations.AddField(
            model_name='peopledetectortest',
            name='negative_samples_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peopledetectortest',
            name='negative_samples_dir',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peopledetectortest',
            name='positive_samples_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peopledetectortest',
            name='positive_samples_dir',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peopledetectortest',
            name='running_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='peopledetectortest',
            name='save_enhaced_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='peopledetectortest',
            name='settings',
            field=models.TextField(default=images.models.settings_asstring),
        ),
        migrations.AddField(
            model_name='peopledetectortest',
            name='true_negatives',
            field=models.PositiveIntegerField(default=0, verbose_name='TN'),
        ),
        migrations.AddField(
            model_name='peopledetectortest',
            name='true_positives',
            field=models.PositiveIntegerField(default=0, verbose_name='TP'),
        ),
    ]
