# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20170411_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peopledetectortest',
            name='duration',
        ),
        migrations.AddField(
            model_name='peopledetectortest',
            name='time_took',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='peopledetectortest',
            name='state',
            field=models.CharField(choices=[('initial', 'initial'), ('running', 'running'), ('finished', 'finished'), ('failed', 'failed')], default='initial', max_length=10),
        ),
    ]
