# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-31 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20170417_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopledetectortest',
            name='discarded_samples_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Discarded Samples'),
        ),
    ]
