# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20170412_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopledetectortest',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='peopledetectortest',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='peopledetectortest',
            name='negative_samples_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Negative Samples'),
        ),
        migrations.AlterField(
            model_name='peopledetectortest',
            name='positive_samples_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Positive Samples'),
        ),
        migrations.AlterField(
            model_name='peopledetectortest',
            name='running_timestamp',
            field=models.DateTimeField(null=True, verbose_name='Executed'),
        ),
    ]
