# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20170412_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopledetectortest',
            name='title',
            field=models.CharField(default='Test', max_length=50),
        ),
    ]
