# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20170412_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopledetectortest',
            name='_accuracy',
            field=models.FloatField(default=0.0),
        ),
    ]
