# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_peopledetectortest__accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopledetectortest',
            name='_total_samples_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
