# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='telegramnotificationhandler',
            name='telegram_bot',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='notifications.TelegramBot'),
            preserve_default=False,
        ),
    ]
