# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20160918_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramnotificationhandler',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
