# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20160918_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramnotificationhandler',
            name='subscribers',
            field=models.ManyToManyField(blank=True, to='notifications.NotificationUserProfile'),
        ),
    ]
