# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-15 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_telegrambot_debug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='debug',
            field=models.BooleanField(default=False, help_text='Enable online evaluation of each image received', verbose_name='Debug enabled'),
        ),
    ]
