# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-17 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20170415_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='module_name',
            field=models.CharField(choices=[('scamera_bot_impl1', 'Impl. v1.0'), ('scamera_bot_impl2', 'Impl. v2.0')], default='scamera_bot_impl1', help_text='Handler module (telegram bot API implementation)', max_length=25, verbose_name='Bot implementation'),
        ),
    ]
